name: 16 Deploy Action
description: Deploy Action

runs:
  using: Checkout repo
  steps:
    - name: Checkout repo
      uses: actions/checkout@v6
    - name: Build
      id: build
      run: |
        echo "Building using directory"
      shell: bash
    - name: Deploy
      id: deploy
      run: |
        echo "Deploying build artifacts"
      shell: bash