name: 16 - 2 - Reusable Workflows
on:
    workflow_dispatch:
jobs:
    mainDeploy:      
        runs-on: ubuntu-latest
        steps:
            - name: deploy
              uses: ./.github/deploy-action
