name: 16 - 2 - Custom Action
on:
    workflow_dispatch:
jobs:
    mainDeploy:      
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
              
            - name: deploy
              uses: ./.github/deploy-action
            
